-- 색상에 WHITE 추가 (기존 DB에서 한 번만 실행)
-- 기본값(DEFAULT)은 기존 DDL과 같게 유지했어요.
ALTER TABLE workspaces MODIFY COLUMN color ENUM('BLUE','PURPLE','GREEN','RED','ORANGE','PINK','GRAY','WHITE') NOT NULL DEFAULT 'BLUE';
ALTER TABLE sprints MODIFY COLUMN color ENUM('BLUE','PURPLE','GREEN','RED','ORANGE','PINK','GRAY','WHITE') NOT NULL DEFAULT 'BLUE';
ALTER TABLE task_statuses MODIFY COLUMN color ENUM('BLUE','PURPLE','GREEN','RED','ORANGE','PINK','GRAY','WHITE') NOT NULL DEFAULT 'BLUE';
ALTER TABLE events MODIFY COLUMN color ENUM('BLUE','PURPLE','GREEN','RED','ORANGE','PINK','GRAY','WHITE') NOT NULL DEFAULT 'PURPLE';
ALTER TABLE block_database_column_options MODIFY COLUMN color ENUM('BLUE','PURPLE','GREEN','RED','ORANGE','PINK','GRAY','WHITE') NOT NULL DEFAULT 'GRAY';
